logging:
  level:
    org:
      org:
        springframework: DEBUG
server:
  port: 8080
  
spring:
  banner:
    image:
      location: classpath:logo.png
  datasource:
    driver-class-name: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:bank_customer_db
    username: sa
  flyway:
    baselineOnMigrate: true
    check-location: true
    locations: classpath:db/migrations
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
